name: Jok
main: com.Jok.Group.Main
version: 1.0
author: jokitv

commands:
   j:
      description: Prints all worlds.
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission> an
   swag:
      description: Test.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission> an